name: Build and Push Docker Image
on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: ktp-chan
  IMAGE_NAME: ktp-chan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.supaperman.net
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_URL }}/${{ env.PROJECT_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          platforms: linux/amd64
